using GdNet.Domain.Entity;
using GdNet.Domain.Entity.Impl;
using System.ComponentModel.DataAnnotations;

namespace Rabbit.SecurityLayer.Domain
{
    public class User : EditableEntityBase, IAggregateRoot
    {
        public User()
            : base(new DefaultStateStrategy(), new EntityAvailableByDefaultStrategy())
        {
        }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        [Required]
        public string DisplayName { get; set; }

        [Required]
        public string Email { get; set; }

        /// <summary>
        /// This is a flag that is calculated from UserConfigurationFlags
        /// </summary>
        [Required]
        public int ConfigurationFlags { get; private set; }

        public string Phone { get; set; }

        /// <summary>
        /// An unique profile (generated by external party)
        /// </summary>
        [Required]
        public string Profile { get; set; }

        public User AddConfigurationFlag(int flag)
        {
            ConfigurationFlags = ConfigurationFlags | flag;
            return this;
        }

        public User RemoveConfigurationFlag(int flag)
        {
            ConfigurationFlags = ConfigurationFlags ^ flag;
            return this;
        }
    }
}
